[package]
name = "finite_fields"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
num = "0.4"
hex = "0.4.3"
sha256 = "1.1.2"
sha2 = "0.10.6"
hmac = "0.12.1"
